-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 20:35:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shows
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shows
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shows` DEFAULT CHARACTER SET utf8 ;
USE `shows` ;

-- -----------------------------------------------------
-- Table `shows`.`shows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shows`.`shows` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `capacidade` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shows`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shows`.`Ingresso` (
  `id` INT NOT NULL,
  `lugar` VARCHAR(45) NULL,
  `shows_id` INT NOT NULL,
  PRIMARY KEY (`id`),
 # INDEX `fk_Ingresso_shows_idx` (`shows_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ingresso_shows`
    FOREIGN KEY (`shows_id`)
    REFERENCES `shows`.`shows` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

create table auditoria(capacidade varchar(100));
DROP TRIGGER before_ingresso_insert;

DELIMITER $$
CREATE TRIGGER before_ingresso_insert
BEFORE INSERT
ON ingresso FOR EACH ROW
BEGIN
    DECLARE qtdeingressos INT;
    
    SELECT COUNT(*) 
    INTO qtdeingressos
    FROM ingresso;
    
    IF (qtdeingressos >= 7) THEN
        insert into auditoria (capacidade) values 
			("capacidade excedida");
    END IF; 
END $$
DELIMITER ;
DELETE FROM INGRESSO;
delete from auditoria;
SELECT * FROM auditoria;
select * from ingresso;
select count(*) from ingresso;
insert into ingresso values(1, 'ABC', 1),
(2, 'ABD', 1),
(3, 'ABE', 1),
(4, 'ABF', 1),
(5, 'ABG', 1),
(6, 'ABH', 1),
(7, 'ABI', 1),
(8, 'ABJ', 1);
insert into ingresso values(9, 'ABK', 1);
select * from auditoria;

use test;
